# Generated by Django 2.1.4 on 2018-12-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nike_name',
            new_name='nick_name',
        ),
    ]
