# Generated by Django 2.1.4 on 2018-12-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsystem', '0003_auto_20181223_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
